### ISSUE TITLE
Boulanger / Venum / Cdiscount and Ventura don't work

### ISSUE THREAD

**Issue by jordantmort** [nherbaut/java-runner-analytics#2]
Bonsoir monsieur,
comme signalé plus tôt en td les sites que je vous ais joint dans l'objet ne fonctionne pas sur firefox
Bien à vous

**Comment by nherbaut** [comment]
[OK] Boulanger
[KO] Venum (les items sont chargés en JS, donc non scrappés)
[KO] CDISCOUNT (protégé par cshield.net)
[KO] Ventura : ne n'ai pas trouvé le site
